// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_App1_JamesUrena.DAL;

#nullable disable

namespace P1_App1_JamesUrena.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251011162452_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_App1_JamesUrena.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("EntradaId");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_App1_JamesUrena.Models.EntradasHuacalesDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_App1_JamesUrena.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Huacales verdes",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Huacales azules",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Huacales negros",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_App1_JamesUrena.Models.EntradasHuacalesDetalles", b =>
                {
                    b.HasOne("P1_App1_JamesUrena.Models.EntradasHuacales", "EntradaHuacales")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_App1_JamesUrena.Models.TiposHuacales", "TipoHuacales")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacales");

                    b.Navigation("TipoHuacales");
                });

            modelBuilder.Entity("P1_App1_JamesUrena.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_App1_JamesUrena.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
